function ascii(value){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^ -~]/g,"?")}
function esc(value){return ascii(value).replace(/([\\()])/g,"\\$1")}
function wrap(value,max=72){const words=ascii(value).split(/\s+/).filter(Boolean),lines=[];let line="";for(const word of words){if((line+" "+word).trim().length>max&&line){lines.push(line);line=word}else line=(line+" "+word).trim()}if(line)lines.push(line);return lines}
function text(lines,x,y,size=11,center=false){return lines.map((line,index)=>`BT /F1 ${size} Tf ${center?`${x-(line.length*size*.27)}`:x} ${y-index*(size+5)} Td (${esc(line)}) Tj ET`).join("\n")}
export function agreementPdf({organization,meetingTitle,date,agreement,members}){
  const commands=["0.07 0.20 0.18 rg",text([organization],54,790,12),"0.83 0.67 0.33 RG 2 w 54 770 m 541 770 l S",text(["VERGADERAFSPRAAK"],297,725,18,true),text([meetingTitle,`Vergaderdatum: ${date}`],297,698,10,true),"0.94 0.97 0.95 rg 54 505 487 150 re f","0.07 0.20 0.18 rg",text(wrap(agreement.agreementText,65),297,620,15,true),text(["Ondertekening bestuursleden"],54,470,13)];
  const list=members.slice(0,10),cols=2,cellW=235,cellH=Math.min(76,360/Math.max(1,Math.ceil(list.length/cols)));
  list.forEach((member,index)=>{const col=index%2,row=Math.floor(index/2),x=54+col*252,y=435-row*cellH;commands.push("0.82 0.86 0.84 RG 0.8 w",`${x} ${y-cellH+7} ${cellW} ${cellH-7} re S`,"0.07 0.20 0.18 rg",text([member.name+(member.role?` - ${member.role}`:"")],x+8,y-14,9));const sig=agreement.signatures?.[member.id];if(sig?.strokes){commands.push("0.08 0.10 0.10 RG 1.2 w");for(const stroke of sig.strokes){if(!stroke.length)continue;const first=stroke[0];commands.push(`${(x+12+first.x*(cellW-24)).toFixed(2)} ${(y-cellH+17+first.y*(cellH-42)).toFixed(2)} m`);for(const point of stroke.slice(1))commands.push(`${(x+12+point.x*(cellW-24)).toFixed(2)} ${(y-cellH+17+point.y*(cellH-42)).toFixed(2)} l`);commands.push("S")}}else commands.push(text(["Handtekening"],x+8,y-cellH+17,7))});
  commands.push("0.35 0.42 0.39 rg",text([`Document gegenereerd op ${new Date().toLocaleDateString("nl-NL")}`],54,28,8));
  const stream=commands.join("\n"),objects=[null,"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf="%PDF-1.4\n",offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=Buffer.byteLength(pdf);pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf)}
