const aliases={
  firstName:["voornaam","first_name","firstname","first name"],lastName:["achternaam","tussenvoegsel_achternaam","last_name","lastname","surname"],fullName:["naam","volledige_naam","name","full_name"],email:["email","e-mail","emailadres","e-mailadres"],phone:["telefoon","telefoonnummer","phone","mobile","mobiel"],iban:["iban","bankrekening","bankrekeningnummer","rekeningnummer"],address:["adres","straat","address"],postalCode:["postcode","postal_code","zipcode","zip"],city:["plaats","woonplaats","stad","city"],profession:["beroep","profession","occupation"],notes:["notitie","notities","opmerking","opmerkingen","notes"]
};
const normalize=value=>String(value??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_");
const cleanIban=value=>String(value||"").replace(/\s+/g,"").toUpperCase();

export function parseCsv(text){
  const source=String(text||"").replace(/^\uFEFF/,""),firstLine=source.split(/\r?\n/,1)[0]||"",delimiter=[[";",(firstLine.match(/;/g)||[]).length],[",",(firstLine.match(/,/g)||[]).length],["\t",(firstLine.match(/\t/g)||[]).length]].sort((a,b)=>b[1]-a[1])[0][0],rows=[];let row=[],cell="",quoted=false;
  for(let index=0;index<source.length;index++){const char=source[index],next=source[index+1];if(char==='"'&&quoted&&next==='"'){cell+='"';index++;}else if(char==='"'){quoted=!quoted;}else if(char===delimiter&&!quoted){row.push(cell);cell="";}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')index++;row.push(cell);if(row.some(value=>String(value).trim()))rows.push(row);row=[];cell="";}else cell+=char;}row.push(cell);if(row.some(value=>String(value).trim()))rows.push(row);return rows;
}

export function inspectDonorCsv(text,existing=[]){
  const matrix=parseCsv(text);if(matrix.length<2)return{headers:matrix[0]||[],rows:[],summary:{total:0,valid:0,errors:0},error:"Het CSV-bestand bevat geen gegevensregels."};if(matrix.length>5001)return{headers:matrix[0],rows:[],summary:{total:matrix.length-1,valid:0,errors:matrix.length-1},error:"Importeer maximaal 5.000 donateurs per keer."};
  const headers=matrix[0].map(normalize),find=key=>headers.findIndex(header=>aliases[key].map(normalize).includes(header)),indexes=Object.fromEntries(Object.keys(aliases).map(key=>[key,find(key)]));if(indexes.firstName<0&&indexes.fullName<0)return{headers:matrix[0],rows:[],summary:{total:matrix.length-1,valid:0,errors:matrix.length-1},error:"Kolom 'voornaam' of 'naam' ontbreekt."};if(indexes.lastName<0&&indexes.fullName<0)return{headers:matrix[0],rows:[],summary:{total:matrix.length-1,valid:0,errors:matrix.length-1},error:"Kolom 'achternaam' of 'naam' ontbreekt."};
  const emails=new Set(existing.map(item=>String(item.email||"").toLowerCase()).filter(Boolean)),ibans=new Set(existing.map(item=>cleanIban(item.iban)).filter(Boolean)),seenEmails=new Set(),seenIbans=new Set();
  const value=(row,key)=>indexes[key]>=0?String(row[indexes[key]]||"").trim():"";const rows=matrix.slice(1).map((row,index)=>{let firstName=value(row,"firstName"),lastName=value(row,"lastName");if((!firstName||!lastName)&&value(row,"fullName")){const parts=value(row,"fullName").split(/\s+/);firstName=firstName||parts.shift()||"";lastName=lastName||parts.join(" ");}const data={firstName,lastName,email:value(row,"email").toLowerCase(),phone:value(row,"phone"),iban:cleanIban(value(row,"iban")),address:value(row,"address"),postalCode:value(row,"postalCode"),city:value(row,"city"),profession:value(row,"profession"),notes:value(row,"notes")},errors=[];if(!data.firstName)errors.push("Voornaam ontbreekt");if(!data.lastName)errors.push("Achternaam ontbreekt");if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))errors.push("Ongeldig e-mailadres");if(data.iban&&!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(data.iban))errors.push("Ongeldig IBAN");if(data.email&&(emails.has(data.email)||seenEmails.has(data.email)))errors.push("E-mailadres bestaat al");if(data.iban&&(ibans.has(data.iban)||seenIbans.has(data.iban)))errors.push("IBAN bestaat al");if(data.email)seenEmails.add(data.email);if(data.iban)seenIbans.add(data.iban);return{row:index+2,status:errors.length?"error":"valid",errors,data};});return{headers:matrix[0],rows,summary:{total:rows.length,valid:rows.filter(row=>row.status==="valid").length,errors:rows.filter(row=>row.status==="error").length}};
}
